import { Component, OnInit, ChangeDetectorRef, ChangeDetectionStrategy, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, Router, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { LucideAngularModule } from 'lucide-angular';
import { ApiService } from '../../../services/api.service';
import { ProjectService } from '../../../services/project.service';
import { ToastService } from '../../../services/toast.service';

declare var Razorpay: any;

interface User {
    id: string;
    name: string;
    email: string;
    userType: 'student' | 'individual' | 'organization';
    referralCode: string;
    referralPoints: number;
}

interface Donation {
    id: string;
    amount: number;
    status: string;
    createdAt: string;
    paymentId?: string;
    request80g?: boolean;
    projectId?: string | null;
    certificateStatus?: string | null;
}

interface DonationSummary {
    totalDonations: number;
    totalAmount: number;
    thisMonthAmount: number;
}

interface ReferralStats {
    referralPoints: number;
    referralCount: number;
    referralCode: string;
    referralLink: string;
    recentReferrals: { name: string; created_at: string }[];
}

interface CertificateRequest {
    id: string;
    panNumber: string;
    status: string;
    certificateNumber: string | null;
    pdfUrl: string | null;
    autoGenerated: boolean;
    issuedAt: string | null;
    requestedAt: string;
    processedAt: string | null;
    donationAmount: number | null;
    donationDate: string | null;
    donationId: string | null;
}

interface ProjectCard {
    id: string;
    slug: string;
    name: string;
    tagline: string | null;
    logo_url: string | null;
    stats: { totalRaised: number; donorCount: number; eventCount: number; donationCount: number };
}

interface EventCard {
    id: string;
    event_name: string;
    event_type: string;
    event_date: string;
    event_location: string;
    description: string | null;
    banner_url: string | null;
    project_id: string | null;
    project_name: string | null;
    project_slug: string | null;
}

interface Accomplishment {
    id: string;
    title: string;
    description: string | null;
    metric_value: string | null;
    metric_unit: string | null;
    icon: string | null;
}

interface ProjectDetail extends ProjectCard {
    description: string | null;
    mission: string | null;
    accomplishments: Accomplishment[];
}

@Component({
    selector: 'app-dashboard',
    standalone: true,
    imports: [CommonModule, RouterLink, FormsModule, LucideAngularModule],
    templateUrl: './dashboard.component.html',
    styleUrl: './dashboard.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DashboardComponent implements OnInit {
    user: User | null = null;
    donations: Donation[] = [];
    summary: DonationSummary = { totalDonations: 0, totalAmount: 0, thisMonthAmount: 0 };
    referralStats: ReferralStats | null = null;
    certificateRequests: CertificateRequest[] = [];
    projects: ProjectCard[] = [];
    events: EventCard[] = [];
    projectDetails: ProjectDetail[] = [];

    activeTab = 'overview';
    showAllDonationsModal = false;
    donationsPreviewCount = 4;
    showAllReferralsModal = false;
    referralsPreviewCount = 4;
    donationAmount = 0;
    // Tree-based donation tiers shown as a static price list. The tier is derived
    // from the number of trees entered; the amount charged (in ₹) is
    // treeCount × pricePerTree for that tier. Bulk tiers are cheaper per tree.
    // `max: null` = "and above" (no upper bound).
    readonly treeTiers = [
        { id: 't1', range: '1-5', min: 1, max: 5 as number | null, pricePerTree: 1999 },
        { id: 't2', range: '6-10', min: 6, max: 10 as number | null, pricePerTree: 1750 },
        { id: 't3', range: '11-20', min: 11, max: 20 as number | null, pricePerTree: 1500 },
        { id: 't4', range: '21-50', min: 21, max: 50 as number | null, pricePerTree: 1250 },
        { id: 't5', range: '50 above', min: 51, max: null as number | null, pricePerTree: 1000 }
    ];
    treeCount: number | null = null;
    // Quick-pick tree counts. Clicking one fills the count; the matching price
    // tier (and amount) is derived automatically.
    readonly treeQuickPicks = [5, 10, 20, 50];
    request80g = false;
    selectedProjectId = '';
    selectedFilter = 'all';
    isLoading = false;
    showDonateModal = false;
    showCertificateModal = false;
    panNumber = '';

    // Post-payment verify overlay — friendly waiting state while the server
    // confirms with Razorpay + writes the donation. Dismissible (verify
    // continues in background even if the user closes it).
    showVerifyingOverlay = false;
    verifyingMessageIndex = 0;
    private verifyingMessageTimer: any = null;
    readonly verifyingMessages = [
        'Thanks for your contribution!',
        'Verifying your payment with the bank…',
        'Almost there…',
        'Wrapping up — saving your donation…'
    ];
    selectedDonationId = '';
    linkCopied = false;

    profile: any = null;
    profileIncomplete = false;
    addressIncomplete = false;
    showAddressPrompt = false;
    showPanPrompt = false;
    panPromptValue = '';
    panPromptFirstName = '';
    panPromptLastName = '';
    private pendingDonation: { amount: number; projectId: string | null } | null = null;
    // Amount carried in via the /dashboard?donate=1&amount=<n> deep-link (rupee projects only).
    private deepLinkAmount: number | null = null;

    constructor(
        private router: Router,
        private route: ActivatedRoute,
        private api: ApiService,
        private projectService: ProjectService,
        private cdr: ChangeDetectorRef,
        private toast: ToastService,
        private zone: NgZone
    ) { }

    ngOnInit(): void {
        this.loadUser();
        this.loadDashboardData();
        this.loadProfile();
        this.loadProjects();
        this.loadEvents();
        this.handleDonateDeepLink();
    }

    /**
     * Deep-link entry from the project page Donate CTA.
     *   /dashboard?donate=1&projectId=<id>&amount=<n>
     * Pre-fills the modal and opens it once projects are loaded.
     * Applies the same profile/address completeness gate as the dashboard Donate buttons.
     */
    private handleDonateDeepLink(): void {
        const q = this.route.snapshot.queryParamMap;
        if (q.get('donate') !== '1') return;

        const projectId = q.get('projectId');
        const amountStr = q.get('amount');
        if (amountStr) {
            const parsed = parseInt(amountStr, 10);
            if (!isNaN(parsed) && parsed > 0) this.deepLinkAmount = parsed;
        }

        // Poll for projects to load (project.service.listActive can take ~200ms).
        // Cap at 5s so a backend hiccup never strands the user with no modal.
        // Wait for both projects AND profile to load so the completeness gate is accurate.
        // Cap at 5s so a backend hiccup never strands the user with no modal.
        const started = Date.now();
        const tick = () => {
            const ready = this.projects.length && this.profile;
            if (ready || Date.now() - started > 5000) {
                if (projectId && this.projects.some(p => p.id === projectId)) {
                    this.selectedProjectId = projectId;
                }
                // Deep-link / post-login intent is explicitly "donate now", so open
                // the modal directly instead of the profile/address prompt gate.
                this.openDonateModal();
                // Consume the deep-link params (replaceUrl) so pressing Back or
                // refreshing this URL doesn't re-trigger the gate/modal again.
                this.router.navigate([], { relativeTo: this.route, queryParams: {}, replaceUrl: true });
                this.cdr.detectChanges();
                return;
            }
            setTimeout(tick, 150);
        };
        setTimeout(tick, 150);
    }

    loadProjects(): void {
        this.projectService.listActive().subscribe({
            next: (res: any) => {
                if (res?.success) {
                    this.projects = res.data || [];
                    if (!this.selectedProjectId && this.projects.length > 0) {
                        this.selectedProjectId = this.projects[0].id;
                    }
                    this.cdr.detectChanges();
                    this.loadDonatedProjectDetails();
                }
            },
            error: () => { }
        });
    }

    loadEvents(): void {
        this.api.getActiveEvents().subscribe({
            next: (res: any) => {
                if (res?.success) {
                    this.events = (res.data || []).slice(0, 3);
                    this.cdr.detectChanges();
                }
            },
            error: () => { }
        });
    }

    /** Fetch full project records (with accomplishments) for projects the user has donated to.
     *  Falls back to the first 2 active projects when the user has no donations yet. */
    private loadDonatedProjectDetails(): void {
        if (!this.projects.length) return;

        const donatedIds = new Set(
            this.donations
                .filter(d => d.status === 'completed' && d.projectId)
                .map(d => d.projectId as string)
        );

        let targets = this.projects.filter(p => donatedIds.has(p.id));
        if (targets.length === 0) targets = this.projects.slice(0, 2);

        const slugs = targets.map(p => p.slug);
        const details: ProjectDetail[] = [];
        let pending = slugs.length;
        if (!pending) return;

        for (const slug of slugs) {
            this.projectService.getBySlug(slug).subscribe({
                next: (res: any) => {
                    if (res?.success && res.data) details.push(res.data);
                },
                error: () => { },
                complete: () => {
                    pending -= 1;
                    if (pending === 0) {
                        this.projectDetails = details;
                        this.cdr.detectChanges();
                    }
                }
            });
        }
    }

    get selectedProject(): ProjectCard | null {
        return this.projects.find(p => p.id === this.selectedProjectId) || null;
    }

    loadUser(): void {
        try {
            const userData = localStorage.getItem('user');
            if (userData && userData !== 'undefined' && userData !== 'null') {
                this.user = JSON.parse(userData);
            } else {
                this.router.navigate(['/login']);
            }
        } catch {
            this.router.navigate(['/login']);
        }
    }

    loadDashboardData(): void {
        const calls: Record<string, any> = {
            summary: this.api.getDonationSummary(),
            donations: this.api.getDonations(this.selectedFilter),
            referrals: this.api.getReferrals()
        };

        if (this.user?.userType === 'organization' || this.user?.userType === 'individual') {
            calls['certificates'] = this.api.getCertificateRequests();
        }

        forkJoin(calls).subscribe({
            next: (res: any) => {
                this.zone.run(() => {
                    if (res.summary?.success) this.summary = res.summary.data;
                    if (res.donations?.success) this.donations = res.donations.data;
                    if (res.referrals?.success) this.referralStats = res.referrals.data;
                    if (res.certificates?.success) this.certificateRequests = res.certificates.data;
                    this.cdr.detectChanges();
                    // Donations now known; refresh donated-to project details (no-op if projects haven't loaded yet — the projects callback will re-run this).
                    this.loadDonatedProjectDetails();
                });
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    loadDonations(): void {
        this.api.getDonations(this.selectedFilter).subscribe({
            next: (res: any) => {
                this.zone.run(() => {
                    if (res.success) { this.donations = res.data; this.cdr.detectChanges(); }
                });
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    loadCertificates(): void {
        this.api.getCertificateRequests().subscribe({
            next: (res: any) => {
                this.zone.run(() => {
                    if (res.success) { this.certificateRequests = res.data; this.cdr.detectChanges(); }
                });
            },
            error: () => { }
        });
    }

    onFilterChange(): void {
        this.loadDonations();
    }

    // Rupee presets for non-tree projects (e.g. Zoo) — the original behaviour.
    readonly amountPresets = [100, 500, 1000, 5000];

    /**
     * True when the selected project is the tree-planting one (ROOTS), which uses
     * the tree-range tabs + per-tree pricing. Every other project (Zoo, etc.)
     * uses the plain rupee presets + custom amount.
     */
    get treeMode(): boolean {
        const p = this.selectedProject;
        if (!p) return false;
        return /root/i.test(p.slug || '') || /root/i.test(p.name || '');
    }

    /** Select a project tab and reset the amount UI to that project's mode. */
    selectProject(id: string): void {
        this.selectedProjectId = id;
        if (this.treeMode) {
            this.treeCount = null;
            this.recomputeAmount();
        } else {
            this.donationAmount = 500;
        }
    }

    /** The price tier whose range contains the current tree count (defaults to the first). */
    get currentTier() {
        const n = this.treeCount;
        if (n != null && Number.isFinite(n)) {
            const t = this.treeTiers.find(t => n >= t.min && (t.max == null || n <= t.max));
            if (t) return t;
        }
        return this.treeTiers[0];
    }

    /** True when treeCount is a whole number of at least 1 (any count maps to a tier). */
    get treeCountValid(): boolean {
        const n = this.treeCount;
        return n != null && Number.isFinite(n) && Number.isInteger(n) && n >= 1;
    }

    /** Quick-pick: fill the exact tree count; the tier and amount derive automatically. */
    pickTreeCount(count: number): void {
        this.treeCount = count;
        this.recomputeAmount();
    }

    /** Recompute the ₹ amount from the tree count and its tier's per-tree price. */
    recomputeAmount(): void {
        const n = this.treeCount ?? 0;
        this.donationAmount = n > 0 ? n * this.currentTier.pricePerTree : 0;
    }

    initiateDonation(): void {
        if (this.treeMode ? !this.treeCountValid : this.donationAmount < 1) return;
        if (this.request80g && !this.profile?.panNumber) {
            this.pendingDonation = { amount: this.donationAmount, projectId: this.selectedProjectId || null };
            this.panPromptValue = '';
            const { first, last } = this.splitName(this.profile?.name || this.user?.name || '');
            this.panPromptFirstName = first;
            this.panPromptLastName = last;
            this.showDonateModal = false;
            this.showPanPrompt = true;
            return;
        }
        this.showDonateModal = false;
        this.startDonationFlow(this.donationAmount, this.request80g, this.selectedProjectId || null);
    }

    private splitName(full: string): { first: string; last: string } {
        const parts = (full || '').trim().split(/\s+/).filter(Boolean);
        if (parts.length === 0) return { first: '', last: '' };
        if (parts.length === 1) return { first: parts[0], last: '' };
        return { first: parts[0], last: parts.slice(1).join(' ') };
    }

    savePanAndContinue(): void {
        const pan = (this.panPromptValue || '').trim().toUpperCase();
        if (pan.length !== 10 || !this.pendingDonation) return;
        const combinedName = `${(this.panPromptFirstName || '').trim()} ${(this.panPromptLastName || '').trim()}`.trim();
        const payload: any = { panNumber: pan };
        if (combinedName) payload.name = combinedName;
        this.isLoading = true;
        this.api.updateProfile(payload).subscribe({
            next: (res: any) => {
                this.zone.run(() => {
                    this.isLoading = false;
                    if (res.success) {
                        if (this.profile) {
                            this.profile.panNumber = pan;
                            if (combinedName) this.profile.name = combinedName;
                        }
                        if (combinedName && this.user) {
                            this.user = { ...this.user, name: combinedName };
                            localStorage.setItem('user', JSON.stringify(this.user));
                        }
                        const pending = this.pendingDonation!;
                        this.showPanPrompt = false;
                        this.pendingDonation = null;
                        this.panPromptValue = '';
                        this.panPromptFirstName = '';
                        this.panPromptLastName = '';
                        this.cdr.detectChanges();
                        this.startDonationFlow(pending.amount, true, pending.projectId);
                    } else {
                        this.toast.error(res.message || 'Failed to save PAN');
                        this.cdr.detectChanges();
                    }
                });
            },
            error: (err: any) => {
                this.zone.run(() => {
                    this.isLoading = false;
                    this.toast.error(err.error?.message || 'Failed to save PAN');
                    this.cdr.detectChanges();
                });
            }
        });
    }

    skipCertAndContinue(): void {
        if (!this.pendingDonation) return;
        const pending = this.pendingDonation;
        this.request80g = false;
        this.showPanPrompt = false;
        this.pendingDonation = null;
        this.panPromptValue = '';
        this.startDonationFlow(pending.amount, false, pending.projectId);
    }

    cancelPanPrompt(): void {
        this.showPanPrompt = false;
        this.pendingDonation = null;
        this.panPromptValue = '';
        this.panPromptFirstName = '';
        this.panPromptLastName = '';
    }

    retryDonation(d: Donation): void {
        if (!d || d.amount < 1) return;
        if (d.status !== 'failed' && d.status !== 'pending') return;
        // For a pending row (Razorpay dismissed), mark it failed first so the
        // dashboard doesn't end up with stacked duplicate pending entries.
        // The follow-up startDonationFlow runs regardless of the cancel outcome
        // so a slow/failing cancel call doesn't block the user from retrying.
        const launch = () => this.startDonationFlow(d.amount, !!d.request80g, d.projectId || null);
        if (d.status === 'pending') {
            this.api.cancelPendingDonation(d.id).subscribe({
                next: () => launch(),
                error: () => launch()
            });
        } else {
            launch();
        }
    }

    private startDonationFlow(amount: number, request80g: boolean, projectId: string | null): void {
        this.isLoading = true;

        this.api.createOrder(amount, request80g, 'donation', projectId).subscribe({
            next: (res: any) => {
                this.isLoading = false;
                if (res.success) {
                    const options = {
                        key: res.data.keyId,
                        amount: res.data.amount,
                        currency: res.data.currency,
                        name: 'ICE Network',
                        description: 'ICE Network Donation',
                        order_id: res.data.orderId,
                        handler: (response: any) => {
                            this.zone.run(() => {
                                this.verifyPayment(response, res.data.donationId);
                            });
                        },
                        prefill: { name: this.user?.name, email: this.user?.email },
                        theme: { color: '#22c55e' },
                        modal: {
                            ondismiss: () => {
                                this.zone.run(() => {
                                    this.isLoading = false;
                                    // Donation row was created server-side before Razorpay opened
                                    // (status='pending'). Refresh history so it shows up with a
                                    // Retry pill instead of waiting for a manual reload.
                                    this.loadDonations();
                                    this.cdr.detectChanges();
                                });
                            }
                        }
                    };
                    const razorpay = new Razorpay(options);
                    razorpay.open();
                }
            },
            error: () => { this.isLoading = false; }
        });
    }

    verifyPayment(response: any, donationId: string): void {
        this.startVerifyingOverlay();
        this.api.verifyPayment({
            razorpayOrderId: response.razorpay_order_id,
            razorpayPaymentId: response.razorpay_payment_id,
            razorpaySignature: response.razorpay_signature,
            donationId
        }).subscribe({
            next: (res: any) => {
                this.zone.run(() => {
                    this.stopVerifyingOverlay();
                    if (res.success) {
                        this.loadDashboardData();
                        this.toast.success('Thank you for your donation!');
                        // 80G auto-gen runs post-commit on the server (a couple of seconds);
                        // poll briefly so the cert flips from pending → approved on the
                        // dashboard without a manual reload.
                        this.pollPendingCertificates();
                    }
                });
            },
            error: () => this.zone.run(() => {
                this.stopVerifyingOverlay();
                this.toast.error('Payment verification failed. Please contact support.');
            })
        });
    }

    hasValidPanOnProfile(): boolean {
        const pan = (this.profile?.panNumber || '').trim();
        return /^[A-Z]{5}[0-9]{4}[A-Z]$/i.test(pan);
    }

    /** A 80G certificate needs a valid PAN and a complete address on the profile. */
    is80gProfileComplete(): boolean {
        const p = this.profile;
        if (!p) return false;
        const addressOk = !!(p.addressLine1 && p.city && p.state && p.pincode);
        return this.hasValidPanOnProfile() && addressOk;
    }

    closeVerifyingOverlay(): void {
        this.stopVerifyingOverlay();
    }

    private startVerifyingOverlay(): void {
        this.verifyingMessageIndex = 0;
        this.showVerifyingOverlay = true;
        this.cdr.detectChanges();
        // Rotate copy every 2.2s. Overlay self-dismisses on verify response,
        // so the timer is bounded by the network round-trip in practice.
        this.verifyingMessageTimer = setInterval(() => {
            this.zone.run(() => {
                this.verifyingMessageIndex =
                    (this.verifyingMessageIndex + 1) % this.verifyingMessages.length;
                this.cdr.detectChanges();
            });
        }, 2200);
    }

    private stopVerifyingOverlay(): void {
        if (this.verifyingMessageTimer) {
            clearInterval(this.verifyingMessageTimer);
            this.verifyingMessageTimer = null;
        }
        this.showVerifyingOverlay = false;
        this.cdr.detectChanges();
    }

    /**
     * After a donation completes, the server kicks off 80G cert generation
     * post-commit (fire-and-forget). Re-fetch cert state AND donations every 2s
     * up to 6 times so both the cert request row and the donation history badge
     * flip from pending → approved without a manual reload.
     */
    private pollPendingCertificates(remaining: number = 6): void {
        if (remaining <= 0) return;
        setTimeout(() => {
            forkJoin({
                certs: this.api.getCertificateRequests(),
                donations: this.api.getDonations(this.selectedFilter)
            }).subscribe({
                next: (res: any) => {
                    this.zone.run(() => {
                        if (res.certs?.success) this.certificateRequests = res.certs.data;
                        if (res.donations?.success) this.donations = res.donations.data;
                        this.cdr.detectChanges();
                        const stillPending =
                            (res.certs?.data || []).some((c: any) => c.donationId && c.status === 'pending') ||
                            (res.donations?.data || []).some((d: any) => d.request80g && d.certificateStatus === 'pending');
                        if (stillPending) this.pollPendingCertificates(remaining - 1);
                    });
                }
            });
        }, 2000);
    }

    openCertificateModal(): void {
        this.selectedDonationId = '';
        this.panNumber = this.profile?.panNumber || '';
        // Load all-time donations so the picker has full data
        this.api.getDonations('all').subscribe({
            next: (res: any) => {
                if (res.success) {
                    this.donations = res.data;
                    this.showCertificateModal = true;
                    this.cdr.detectChanges();
                }
            }
        });
        this.loadCertificates();
    }

    requestCertificate(): void {
        if (!this.panNumber || !this.selectedDonationId) return;

        this.isLoading = true;

        this.api.requestCertificate(this.panNumber, this.selectedDonationId).subscribe({
            next: (res: any) => {
                this.isLoading = false;
                if (res.success) {
                    this.toast.success('Certificate request submitted successfully!');
                    this.showCertificateModal = false;
                    this.panNumber = '';
                    this.selectedDonationId = '';
                    this.loadCertificates();
                    this.loadDonations();
                } else {
                    this.toast.error(res.message || 'Failed to submit request');
                }
            },
            error: (err: any) => {
                this.isLoading = false;
                this.toast.error(err.error?.message || 'Failed to submit request');
            }
        });
    }

    copyReferralLink(): void {
        if (this.referralStats?.referralLink) {
            navigator.clipboard.writeText(this.referralStats.referralLink);
            this.linkCopied = true;
            setTimeout(() => this.linkCopied = false, 2000);
        }
    }

    shareOnWhatsApp(): void {
        if (this.referralStats?.referralLink) {
            const text = `Join ICE Network — for a healthier, greener city! Use my referral link: ${this.referralStats.referralLink}`;
            window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
        }
    }

    shareOnTwitter(): void {
        if (this.referralStats?.referralLink) {
            const text = `Join ICE Network — for a healthier, greener city!`;
            window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(this.referralStats.referralLink)}`, '_blank');
        }
    }

    get eligibleDonations(): Donation[] {
        const certDonationIds = new Set(
            this.certificateRequests.filter(c => c.donationId).map(c => c.donationId)
        );
        return this.donations.filter(d => d.status === 'completed' && !certDonationIds.has(d.id));
    }

    getCertStatusClass(status: string): string {
        switch (status) {
            case 'approved': return 'status-approved';
            case 'rejected': return 'status-rejected';
            case 'processing': return 'status-processing';
            default: return 'status-pending';
        }
    }

    loadProfile(): void {
        this.api.getProfile().subscribe({
            next: (res: any) => {
                if (res.success) {
                    this.profile = res.data;
                    this.checkProfileComplete();
                    this.cdr.detectChanges();
                }
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    checkProfileComplete(): void {
        if (!this.profile) return;
        const type = this.profile.userType;
        if (type === 'student') {
            this.profileIncomplete = !this.profile.classGrade || !this.profile.schoolName;
        } else if (type === 'organization') {
            this.profileIncomplete = !this.profile.organizationName || !this.profile.panNumber;
        } else {
            this.profileIncomplete = false;
        }
        this.addressIncomplete = !this.profile.addressLine1 || !this.profile.city || !this.profile.state || !this.profile.pincode;
    }

    onDonateClick(): void {
        if (this.profileIncomplete || this.addressIncomplete) {
            this.showAddressPrompt = true;
        } else {
            this.openDonateModal();
        }
    }

    /** Open the donate modal with fresh defaults (bypasses the profile/address gate). */
    openDonateModal(): void {
        if (this.treeMode) {
            // Tree project: count empty until the donor picks or types one.
            this.treeCount = null;
            this.recomputeAmount();
        } else {
            // Rupee project: use the deep-link amount if present, else default.
            this.donationAmount = this.deepLinkAmount ?? 500;
            this.deepLinkAmount = null;
        }
        this.showDonateModal = true;
    }

    goToProfile(): void {
        this.router.navigate(['/profile']);
    }

    logout(): void {
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        this.router.navigate(['/login']);
    }

    formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-IN', {
            day: 'numeric', month: 'short', year: 'numeric'
        });
    }

    formatEventDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-IN', {
            weekday: 'short', day: 'numeric', month: 'short'
        });
    }

    get hasDonatedProjects(): boolean {
        const donatedIds = new Set(
            this.donations
                .filter(d => d.status === 'completed' && d.projectId)
                .map(d => d.projectId as string)
        );
        return donatedIds.size > 0;
    }

    truncate(text: string | null | undefined, max: number): string {
        if (!text) return '';
        return text.length > max ? text.slice(0, max).trimEnd() + '…' : text;
    }

    downloadCertificate(cert: CertificateRequest): void {
        if (!cert.pdfUrl) return;
        this.api.downloadCertificateAsUser(cert.id).subscribe({
            next: (blob: Blob) => {
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${cert.certificateNumber || cert.id}.pdf`;
                a.click();
                URL.revokeObjectURL(url);
            },
            error: () => this.toast.error('Failed to download certificate.')
        });
    }

    formatCurrency(amount: number): string {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency', currency: 'INR', maximumFractionDigits: 0
        }).format(amount);
    }

    getInitials(name: string | undefined): string {
        if (!name) return '?';
        return name.split(' ').filter(Boolean).map(w => w[0]).join('').toUpperCase().slice(0, 2);
    }
}
