import { Component, OnInit, ChangeDetectorRef, ChangeDetectionStrategy, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { LucideAngularModule } from 'lucide-angular';
import { ApiService } from '../../../services/api.service';
import { ProjectService } from '../../../services/project.service';
import { ToastService } from '../../../services/toast.service';

declare var Razorpay: any;

interface User {
    id: string;
    name: string;
    email: string;
    userType: 'student' | 'individual' | 'organization';
    referralCode: string;
    referralPoints: number;
}

interface Donation {
    id: string;
    amount: number;
    status: string;
    createdAt: string;
    paymentId?: string;
    request80g?: boolean;
    projectId?: string | null;
    certificateStatus?: string | null;
}

interface DonationSummary {
    totalDonations: number;
    totalAmount: number;
    thisMonthAmount: number;
}

interface ReferralStats {
    referralPoints: number;
    referralCount: number;
    referralCode: string;
    referralLink: string;
    recentReferrals: { name: string; created_at: string }[];
}

interface CertificateRequest {
    id: string;
    panNumber: string;
    status: string;
    certificateNumber: string | null;
    pdfUrl: string | null;
    autoGenerated: boolean;
    issuedAt: string | null;
    requestedAt: string;
    processedAt: string | null;
    donationAmount: number | null;
    donationDate: string | null;
    donationId: string | null;
}

interface ProjectCard {
    id: string;
    slug: string;
    name: string;
    tagline: string | null;
    logo_url: string | null;
    stats: { totalRaised: number; donorCount: number; eventCount: number; donationCount: number };
}

interface EventCard {
    id: string;
    event_name: string;
    event_type: string;
    event_date: string;
    event_location: string;
    description: string | null;
    banner_url: string | null;
    project_id: string | null;
    project_name: string | null;
    project_slug: string | null;
}

interface Accomplishment {
    id: string;
    title: string;
    description: string | null;
    metric_value: string | null;
    metric_unit: string | null;
    icon: string | null;
}

interface ProjectDetail extends ProjectCard {
    description: string | null;
    mission: string | null;
    accomplishments: Accomplishment[];
}

@Component({
    selector: 'app-dashboard',
    standalone: true,
    imports: [CommonModule, RouterLink, FormsModule, LucideAngularModule],
    templateUrl: './dashboard.component.html',
    styleUrl: './dashboard.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DashboardComponent implements OnInit {
    user: User | null = null;
    donations: Donation[] = [];
    summary: DonationSummary = { totalDonations: 0, totalAmount: 0, thisMonthAmount: 0 };
    referralStats: ReferralStats | null = null;
    certificateRequests: CertificateRequest[] = [];
    projects: ProjectCard[] = [];
    events: EventCard[] = [];
    projectDetails: ProjectDetail[] = [];

    activeTab = 'overview';
    donationAmount = 100;
    request80g = false;
    selectedProjectId = '';
    selectedFilter = 'all';
    isLoading = false;
    showDonateModal = false;
    showCertificateModal = false;
    panNumber = '';
    selectedDonationId = '';
    linkCopied = false;

    profile: any = null;
    profileIncomplete = false;
    addressIncomplete = false;
    showAddressPrompt = false;

    constructor(
        private router: Router,
        private api: ApiService,
        private projectService: ProjectService,
        private cdr: ChangeDetectorRef,
        private toast: ToastService,
        private zone: NgZone
    ) { }

    ngOnInit(): void {
        this.loadUser();
        this.loadDashboardData();
        this.loadProfile();
        this.loadProjects();
        this.loadEvents();
    }

    loadProjects(): void {
        this.projectService.listActive().subscribe({
            next: (res: any) => {
                if (res?.success) {
                    this.projects = res.data || [];
                    if (!this.selectedProjectId && this.projects.length > 0) {
                        this.selectedProjectId = this.projects[0].id;
                    }
                    this.cdr.detectChanges();
                    this.loadDonatedProjectDetails();
                }
            },
            error: () => { }
        });
    }

    loadEvents(): void {
        this.api.getActiveEvents().subscribe({
            next: (res: any) => {
                if (res?.success) {
                    this.events = (res.data || []).slice(0, 3);
                    this.cdr.detectChanges();
                }
            },
            error: () => { }
        });
    }

    /** Fetch full project records (with accomplishments) for projects the user has donated to.
     *  Falls back to the first 2 active projects when the user has no donations yet. */
    private loadDonatedProjectDetails(): void {
        if (!this.projects.length) return;

        const donatedIds = new Set(
            this.donations
                .filter(d => d.status === 'completed' && d.projectId)
                .map(d => d.projectId as string)
        );

        let targets = this.projects.filter(p => donatedIds.has(p.id));
        if (targets.length === 0) targets = this.projects.slice(0, 2);

        const slugs = targets.map(p => p.slug);
        const details: ProjectDetail[] = [];
        let pending = slugs.length;
        if (!pending) return;

        for (const slug of slugs) {
            this.projectService.getBySlug(slug).subscribe({
                next: (res: any) => {
                    if (res?.success && res.data) details.push(res.data);
                },
                error: () => { },
                complete: () => {
                    pending -= 1;
                    if (pending === 0) {
                        this.projectDetails = details;
                        this.cdr.detectChanges();
                    }
                }
            });
        }
    }

    get selectedProject(): ProjectCard | null {
        return this.projects.find(p => p.id === this.selectedProjectId) || null;
    }

    loadUser(): void {
        try {
            const userData = localStorage.getItem('user');
            if (userData && userData !== 'undefined' && userData !== 'null') {
                this.user = JSON.parse(userData);
            } else {
                this.router.navigate(['/login']);
            }
        } catch {
            this.router.navigate(['/login']);
        }
    }

    loadDashboardData(): void {
        const calls: Record<string, any> = {
            summary: this.api.getDonationSummary(),
            donations: this.api.getDonations(this.selectedFilter),
            referrals: this.api.getReferrals()
        };

        if (this.user?.userType === 'organization' || this.user?.userType === 'individual') {
            calls['certificates'] = this.api.getCertificateRequests();
        }

        forkJoin(calls).subscribe({
            next: (res: any) => {
                if (res.summary?.success) this.summary = res.summary.data;
                if (res.donations?.success) this.donations = res.donations.data;
                if (res.referrals?.success) this.referralStats = res.referrals.data;
                if (res.certificates?.success) this.certificateRequests = res.certificates.data;
                this.cdr.detectChanges();
                // Donations now known; refresh donated-to project details (no-op if projects haven't loaded yet — the projects callback will re-run this).
                this.loadDonatedProjectDetails();
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    loadDonations(): void {
        this.api.getDonations(this.selectedFilter).subscribe({
            next: (res: any) => {
                if (res.success) { this.donations = res.data; this.cdr.detectChanges(); }
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    loadCertificates(): void {
        this.api.getCertificateRequests().subscribe({
            next: (res: any) => {
                if (res.success) { this.certificateRequests = res.data; this.cdr.detectChanges(); }
            },
            error: () => { }
        });
    }

    onFilterChange(): void {
        this.loadDonations();
    }

    initiateDonation(): void {
        if (this.donationAmount < 1) return;
        this.showDonateModal = false;
        this.startDonationFlow(this.donationAmount, this.request80g, this.selectedProjectId || null);
    }

    retryDonation(d: Donation): void {
        if (!d || d.status !== 'failed' || d.amount < 1) return;
        this.startDonationFlow(d.amount, !!d.request80g, d.projectId || null);
    }

    private startDonationFlow(amount: number, request80g: boolean, projectId: string | null): void {
        this.isLoading = true;

        this.api.createOrder(amount, request80g, 'donation', projectId).subscribe({
            next: (res: any) => {
                this.isLoading = false;
                if (res.success) {
                    const options = {
                        key: res.data.keyId,
                        amount: res.data.amount,
                        currency: res.data.currency,
                        name: 'ICE Network',
                        description: 'ICE Network Donation',
                        order_id: res.data.orderId,
                        handler: (response: any) => {
                            this.zone.run(() => {
                                this.verifyPayment(response, res.data.donationId);
                            });
                        },
                        prefill: { name: this.user?.name, email: this.user?.email },
                        theme: { color: '#22c55e' },
                        modal: {
                            ondismiss: () => {
                                this.zone.run(() => {
                                    this.isLoading = false;
                                    this.cdr.detectChanges();
                                });
                            }
                        }
                    };
                    const razorpay = new Razorpay(options);
                    razorpay.open();
                }
            },
            error: () => { this.isLoading = false; }
        });
    }

    verifyPayment(response: any, donationId: string): void {
        this.api.verifyPayment({
            razorpayOrderId: response.razorpay_order_id,
            razorpayPaymentId: response.razorpay_payment_id,
            razorpaySignature: response.razorpay_signature,
            donationId
        }).subscribe({
            next: (res: any) => {
                if (res.success) {
                    this.loadDashboardData();
                    this.toast.success('Thank you for your donation!');
                }
            },
            error: () => this.toast.error('Payment verification failed. Please contact support.')
        });
    }

    openCertificateModal(): void {
        this.selectedDonationId = '';
        this.panNumber = this.profile?.panNumber || '';
        // Load all-time donations so the picker has full data
        this.api.getDonations('all').subscribe({
            next: (res: any) => {
                if (res.success) {
                    this.donations = res.data;
                    this.showCertificateModal = true;
                    this.cdr.detectChanges();
                }
            }
        });
        this.loadCertificates();
    }

    requestCertificate(): void {
        if (!this.panNumber || !this.selectedDonationId) return;

        this.isLoading = true;

        this.api.requestCertificate(this.panNumber, this.selectedDonationId).subscribe({
            next: (res: any) => {
                this.isLoading = false;
                if (res.success) {
                    this.toast.success('Certificate request submitted successfully!');
                    this.showCertificateModal = false;
                    this.panNumber = '';
                    this.selectedDonationId = '';
                    this.loadCertificates();
                    this.loadDonations();
                } else {
                    this.toast.error(res.message || 'Failed to submit request');
                }
            },
            error: (err: any) => {
                this.isLoading = false;
                this.toast.error(err.error?.message || 'Failed to submit request');
            }
        });
    }

    copyReferralLink(): void {
        if (this.referralStats?.referralLink) {
            navigator.clipboard.writeText(this.referralStats.referralLink);
            this.linkCopied = true;
            setTimeout(() => this.linkCopied = false, 2000);
        }
    }

    shareOnWhatsApp(): void {
        if (this.referralStats?.referralLink) {
            const text = `Join ICE Network — for a healthier, greener city! Use my referral link: ${this.referralStats.referralLink}`;
            window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
        }
    }

    shareOnTwitter(): void {
        if (this.referralStats?.referralLink) {
            const text = `Join ICE Network — for a healthier, greener city!`;
            window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(this.referralStats.referralLink)}`, '_blank');
        }
    }

    get eligibleDonations(): Donation[] {
        const certDonationIds = new Set(
            this.certificateRequests.filter(c => c.donationId).map(c => c.donationId)
        );
        return this.donations.filter(d => d.status === 'completed' && !certDonationIds.has(d.id));
    }

    getCertStatusClass(status: string): string {
        switch (status) {
            case 'approved': return 'status-approved';
            case 'rejected': return 'status-rejected';
            case 'processing': return 'status-processing';
            default: return 'status-pending';
        }
    }

    loadProfile(): void {
        this.api.getProfile().subscribe({
            next: (res: any) => {
                if (res.success) {
                    this.profile = res.data;
                    this.checkProfileComplete();
                    this.cdr.detectChanges();
                }
            },
            error: (err: any) => {
                if (err.status === 401 || err.status === 403) this.logout();
            }
        });
    }

    checkProfileComplete(): void {
        if (!this.profile) return;
        const type = this.profile.userType;
        if (type === 'student') {
            this.profileIncomplete = !this.profile.classGrade || !this.profile.schoolName;
        } else if (type === 'organization') {
            this.profileIncomplete = !this.profile.organizationName || !this.profile.panNumber;
        } else {
            this.profileIncomplete = false;
        }
        this.addressIncomplete = !this.profile.addressLine1 || !this.profile.city || !this.profile.state || !this.profile.pincode;
    }

    onDonateClick(): void {
        if (this.addressIncomplete) {
            this.showAddressPrompt = true;
        } else {
            this.showDonateModal = true;
        }
    }

    goToProfile(): void {
        this.router.navigate(['/profile']);
    }

    logout(): void {
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        this.router.navigate(['/login']);
    }

    formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-IN', {
            day: 'numeric', month: 'short', year: 'numeric'
        });
    }

    formatEventDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-IN', {
            weekday: 'short', day: 'numeric', month: 'short'
        });
    }

    get hasDonatedProjects(): boolean {
        const donatedIds = new Set(
            this.donations
                .filter(d => d.status === 'completed' && d.projectId)
                .map(d => d.projectId as string)
        );
        return donatedIds.size > 0;
    }

    truncate(text: string | null | undefined, max: number): string {
        if (!text) return '';
        return text.length > max ? text.slice(0, max).trimEnd() + '…' : text;
    }

    downloadCertificate(cert: CertificateRequest): void {
        if (!cert.pdfUrl) return;
        this.api.downloadCertificateAsUser(cert.id).subscribe({
            next: (blob: Blob) => {
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${cert.certificateNumber || cert.id}.pdf`;
                a.click();
                URL.revokeObjectURL(url);
            },
            error: () => this.toast.error('Failed to download certificate.')
        });
    }

    formatCurrency(amount: number): string {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency', currency: 'INR', maximumFractionDigits: 0
        }).format(amount);
    }

    getInitials(name: string | undefined): string {
        if (!name) return '?';
        return name.split(' ').filter(Boolean).map(w => w[0]).join('').toUpperCase().slice(0, 2);
    }
}
