import { Component, OnInit, ChangeDetectorRef, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { ApiService } from '../../../services/api.service';
import { environment } from '../../../../environments/environment';
import { LucideAngularModule } from 'lucide-angular';

interface CertificateRequest {
    id: string;
    type: string;
    userName: string;
    userEmail: string;
    panNumber: string;
    status: string;
    requestedAt: string;
    processedAt: string | null;
    donationAmount: number | null;
    certificateNumber: string | null;
    pdfUrl: string | null;
    autoGenerated: boolean;
    generationAttempts: number;
    lastGenerationError: string | null;
    issuedAt: string | null;
}

@Component({
    selector: 'app-admin-certificates',
    standalone: true,
    imports: [CommonModule, RouterModule, LucideAngularModule],
    templateUrl: './admin-certificates.component.html',
    styleUrl: './admin-certificates.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AdminCertificatesComponent implements OnInit {
    certificates: CertificateRequest[] = [];
    pagination = { page: 1, totalPages: 1, total: 0 };
    typeFilter: '' | '80g' | 'csr_receipt' = '';

    constructor(
        private router: Router,
        private api: ApiService,
        private cdr: ChangeDetectorRef
    ) { }

    ngOnInit(): void {
        this.loadCertificates();
    }

    setTypeFilter(type: '' | '80g' | 'csr_receipt'): void {
        this.typeFilter = type;
        this.loadCertificates(1);
    }

    loadCertificates(page: number = 1): void {
        this.api.getAdminCertificates(20, page, undefined, this.typeFilter || undefined).subscribe({
            next: (res: any) => {
                if (res.success) {
                    const requests = res.data?.requests || res.data || [];
                    this.certificates = Array.isArray(requests) ? requests.map((r: any) => ({
                        id: r.id,
                        type: r.type || '80g',
                        userName: r.user_name,
                        userEmail: r.user_email,
                        panNumber: r.pan_number,
                        donationAmount: r.donation_amount,
                        requestedAt: r.requested_at,
                        processedAt: r.processed_at || null,
                        status: r.status,
                        adminNotes: r.admin_notes,
                        certificateNumber: r.certificate_number || null,
                        pdfUrl: r.pdf_url || null,
                        autoGenerated: !!r.auto_generated,
                        generationAttempts: r.generation_attempts || 0,
                        lastGenerationError: r.last_generation_error || null,
                        issuedAt: r.issued_at || null
                    })) : [];
                    this.pagination = res.data?.pagination || this.pagination;
                    this.cdr.detectChanges();
                }
            },
            error: () => { }
        });
    }

    updateCertificateStatus(certId: string, status: string): void {
        this.api.updateCertificateStatus(certId, status).subscribe({
            next: (res: any) => {
                if (res.success) this.loadCertificates(this.pagination.page);
            },
            error: () => { }
        });
    }

    regenerateCertificate(certId: string): void {
        this.api.regenerateCertificate(certId).subscribe({
            next: (res: any) => {
                if (res.success) this.loadCertificates(this.pagination.page);
            },
            error: (err: any) => {
                alert(err?.error?.message || 'Regeneration failed.');
            }
        });
    }

    downloadCertificate(cert: CertificateRequest): void {
        if (!cert.pdfUrl) return;
        this.api.downloadCertificateAsAdmin(cert.id).subscribe({
            next: (blob: Blob) => {
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${cert.certificateNumber || cert.id}.pdf`;
                a.click();
                URL.revokeObjectURL(url);
            },
            error: () => alert('Download failed.')
        });
    }

    exportCertificates(): void {
        const token = localStorage.getItem('adminToken');
        if (!token) return;

        const qs = this.typeFilter ? `?type=${encodeURIComponent(this.typeFilter)}` : '';
        const filename = this.typeFilter === 'csr_receipt' ? 'csr-receipts.xlsx'
                       : this.typeFilter === '80g'         ? '80g-certificates.xlsx'
                       : 'tax-receipts.xlsx';

        fetch(`${environment.apiUrl}/admin/certificates/export${qs}`, {
            headers: { 'Authorization': `Bearer ${token}` }
        }).then(res => res.blob()).then(blob => {
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            a.click();
        }).catch(err => console.error('Export failed:', err));
    }

    getCertStatusClass(status: string): string {
        switch (status) {
            case 'approved': return 'status-approved';
            case 'rejected': return 'status-rejected';
            case 'processing': return 'status-processing';
            default: return 'status-pending';
        }
    }

    formatDate(dateString: string): string {
        return new Date(dateString).toLocaleDateString('en-IN', {
            day: 'numeric', month: 'short', year: 'numeric'
        });
    }

    formatCurrency(amount: number): string {
        return new Intl.NumberFormat('en-IN', {
            style: 'currency', currency: 'INR', maximumFractionDigits: 0
        }).format(amount);
    }
}
