/**
 * Tamil Nadu cities and towns, for the volunteer city dropdown.
 *
 * Kept in one place so the admin filter and the public registration form can never drift
 * apart — a filter offering a city the form cannot produce would match nothing.
 *
 * The city filter matches on a partial string server-side, so a stored value like
 * "Chennai, TN" or one with a stray space is still found by picking "Chennai" here.
 */
export const TAMIL_NADU_CITIES: string[] = [
    'Ambur',
    'Arakkonam',
    'Ariyalur',
    'Aruppukottai',
    'Attur',
    'Chengalpattu',
    'Chennai',
    'Chidambaram',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Gudiyatham',
    'Hosur',
    'Kanchipuram',
    'Kanyakumari',
    'Karaikudi',
    'Karur',
    'Krishnagiri',
    'Kumbakonam',
    'Madurai',
    'Mayiladuthurai',
    'Mettupalayam',
    'Nagapattinam',
    'Nagercoil',
    'Namakkal',
    'Neyveli',
    'Ooty (Udhagamandalam)',
    'Palani',
    'Paramakudi',
    'Perambalur',
    'Pollachi',
    'Pudukkottai',
    'Rajapalayam',
    'Ramanathapuram',
    'Ranipet',
    'Salem',
    'Sivagangai',
    'Sivakasi',
    'Tenkasi',
    'Thanjavur',
    'Theni',
    'Thoothukudi (Tuticorin)',
    'Tiruchirappalli (Trichy)',
    'Tirunelveli',
    'Tirupathur',
    'Tiruppur',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Vaniyambadi',
    'Vellore',
    'Villupuram',
    'Virudhunagar',
];
